locobot: #namespace

    # path setup
    ros_ws_abspath: "/home/developer/low_cost_ws"
    ros_ws_src_path: "src/pyrobot/robots/LoCoBot/thirdparty"
    # Fetch Task Realated parameters
    n_actions: 4 # X+/-,Y+/-,Z+/ 5 joint delta
    n_observations: 11 # XYZ of the TCP and the distance from GOAL
    n_max_iterations: 50
    position_ee_max: 1.0
    position_ee_min: -1.0
    threshold_error: 0.05
    use_random_goal: False
    random_target_range: 0.25

    initial_joint_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      joint_1: -1.71341686e-05
      joint_2: 6.71842537e-03
      joint_3: 7.30950843e-03
      joint_4: 3.80347137e-03
      joint_5: -5.22919115e-05

    initial_ee_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      x: 4.11812983e-01
      y: 9.47465341e-05
      z: 4.04977648e-01

    goal_ee_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      #x: 0.339
      #y: 0.0116
      #z: 0.255
      x: 0.32126746
      y: -0.03747156
      z: 0.26531804

    position_delta: 0.1 # Increments of Decrements in the X/Y/Z positions each action step

    step_punishment: -1
    #closer_reward: 10
    #impossible_movement_punishement: -100
    reached_goal_reward: 0

    max_distance_from_ee_to_goal: 3.0 # Maximum distance from EE to the desired GOAL EE
