import numpy as np
import os
import matplotlib.pyplot as plt

pwd = os.path.dirname(os.path.realpath(__file__))
mujoco_joint_1_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_1.txt'))
mujoco_joint_1_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_1_eff_x.txt'))
mujoco_joint_1_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_1_eff_y.txt'))
mujoco_joint_1_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_1_eff_z.txt'))
mujoco_joint_1 = np.loadtxt(mujoco_joint_1_dir)
mujoco_joint_1_eff_x = np.loadtxt(mujoco_joint_1_eff_x_dir)
mujoco_joint_1_eff_y = np.loadtxt(mujoco_joint_1_eff_y_dir)
mujoco_joint_1_eff_z = np.loadtxt(mujoco_joint_1_eff_z_dir)

mujoco_joint_2_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_2.txt'))
mujoco_joint_2_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_2_eff_x.txt'))
mujoco_joint_2_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_2_eff_y.txt'))
mujoco_joint_2_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_2_eff_z.txt'))
mujoco_joint_2 = np.loadtxt(mujoco_joint_2_dir)
mujoco_joint_2_eff_x = np.loadtxt(mujoco_joint_2_eff_x_dir)
mujoco_joint_2_eff_y = np.loadtxt(mujoco_joint_2_eff_y_dir)
mujoco_joint_2_eff_z = np.loadtxt(mujoco_joint_2_eff_z_dir)

mujoco_joint_3_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_3.txt'))
mujoco_joint_3_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_3_eff_x.txt'))
mujoco_joint_3_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_3_eff_y.txt'))
mujoco_joint_3_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_3_eff_z.txt'))
mujoco_joint_3 = np.loadtxt(mujoco_joint_3_dir)
mujoco_joint_3_eff_x = np.loadtxt(mujoco_joint_3_eff_x_dir)
mujoco_joint_3_eff_y = np.loadtxt(mujoco_joint_3_eff_y_dir)
mujoco_joint_3_eff_z = np.loadtxt(mujoco_joint_3_eff_z_dir)

mujoco_joint_4_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_4.txt'))
mujoco_joint_4_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_4_eff_x.txt'))
mujoco_joint_4_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_4_eff_y.txt'))
mujoco_joint_4_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'MuJoCo', 'joint_4_eff_z.txt'))
mujoco_joint_4 = np.loadtxt(mujoco_joint_4_dir)
mujoco_joint_4_eff_x = np.loadtxt(mujoco_joint_4_eff_x_dir)
mujoco_joint_4_eff_y = np.loadtxt(mujoco_joint_4_eff_y_dir)
mujoco_joint_4_eff_z = np.loadtxt(mujoco_joint_4_eff_z_dir)
########################################################################
gazebo_joint_1_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_1.txt'))
gazebo_joint_1_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_1_eff_x.txt'))
gazebo_joint_1_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_1_eff_y.txt'))
gazebo_joint_1_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_1_eff_z.txt'))
gazebo_joint_1 = np.loadtxt(gazebo_joint_1_dir)
gazebo_joint_1_eff_x = np.loadtxt(gazebo_joint_1_eff_x_dir)
gazebo_joint_1_eff_y = np.loadtxt(gazebo_joint_1_eff_y_dir)
gazebo_joint_1_eff_z = np.loadtxt(gazebo_joint_1_eff_z_dir)

gazebo_joint_2_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_2.txt'))
gazebo_joint_2_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_2_eff_x.txt'))
gazebo_joint_2_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_2_eff_y.txt'))
gazebo_joint_2_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_2_eff_z.txt'))
gazebo_joint_2 = np.loadtxt(gazebo_joint_2_dir)
gazebo_joint_2_eff_x = np.loadtxt(gazebo_joint_2_eff_x_dir)
gazebo_joint_2_eff_y = np.loadtxt(gazebo_joint_2_eff_y_dir)
gazebo_joint_2_eff_z = np.loadtxt(gazebo_joint_2_eff_z_dir)

gazebo_joint_3_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_3.txt'))
gazebo_joint_3_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_3_eff_x.txt'))
gazebo_joint_3_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_3_eff_y.txt'))
gazebo_joint_3_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_3_eff_z.txt'))
gazebo_joint_3 = np.loadtxt(gazebo_joint_3_dir)
gazebo_joint_3_eff_x = np.loadtxt(gazebo_joint_3_eff_x_dir)
gazebo_joint_3_eff_y = np.loadtxt(gazebo_joint_3_eff_y_dir)
gazebo_joint_3_eff_z = np.loadtxt(gazebo_joint_3_eff_z_dir)

gazebo_joint_4_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_4.txt'))
gazebo_joint_4_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_4_eff_x.txt'))
gazebo_joint_4_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_4_eff_y.txt'))
gazebo_joint_4_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Gazebo', 'gazebo_joint_4_eff_z.txt'))
gazebo_joint_4 = np.loadtxt(gazebo_joint_4_dir)
gazebo_joint_4_eff_x = np.loadtxt(gazebo_joint_4_eff_x_dir)
gazebo_joint_4_eff_y = np.loadtxt(gazebo_joint_4_eff_y_dir)
gazebo_joint_4_eff_z = np.loadtxt(gazebo_joint_4_eff_z_dir)
#########################################################################
real_joint_1_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_1.txt'))
real_joint_1_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_1_eff_x.txt'))
real_joint_1_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_1_eff_y.txt'))
real_joint_1_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_1_eff_z.txt'))
real_joint_1 = np.loadtxt(real_joint_1_dir)
real_joint_1_eff_x = np.loadtxt(real_joint_1_eff_x_dir)
real_joint_1_eff_y = np.loadtxt(real_joint_1_eff_y_dir)
real_joint_1_eff_z = np.loadtxt(real_joint_1_eff_z_dir)

real_joint_2_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_2.txt'))
real_joint_2_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_2_eff_x.txt'))
real_joint_2_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_2_eff_y.txt'))
real_joint_2_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_2_eff_z.txt'))
real_joint_2 = np.loadtxt(real_joint_2_dir)
real_joint_2_eff_x = np.loadtxt(real_joint_2_eff_x_dir)
real_joint_2_eff_y = np.loadtxt(real_joint_2_eff_y_dir)
real_joint_2_eff_z = np.loadtxt(real_joint_2_eff_z_dir)

real_joint_3_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_3.txt'))
real_joint_3_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_3_eff_x.txt'))
real_joint_3_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_3_eff_y.txt'))
real_joint_3_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_3_eff_z.txt'))
real_joint_3 = np.loadtxt(real_joint_3_dir)
real_joint_3_eff_x = np.loadtxt(real_joint_3_eff_x_dir)
real_joint_3_eff_y = np.loadtxt(real_joint_3_eff_y_dir)
real_joint_3_eff_z = np.loadtxt(real_joint_3_eff_z_dir)

real_joint_4_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_4.txt'))
real_joint_4_eff_x_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_4_eff_x.txt'))
real_joint_4_eff_y_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_4_eff_y.txt'))
real_joint_4_eff_z_dir = os.path.abspath(os.path.join(pwd, 'Comparison', 'Real', 'real_joint_4_eff_z.txt'))
real_joint_4 = np.loadtxt(real_joint_4_dir)
real_joint_4_eff_x = np.loadtxt(real_joint_4_eff_x_dir)
real_joint_4_eff_y = np.loadtxt(real_joint_4_eff_y_dir)
real_joint_4_eff_z = np.loadtxt(real_joint_4_eff_z_dir)


fig, ax = plt.subplots(2,2)
#fig.suptitle("Desired Joint Position vs Actual Joint Positions")
fig.suptitle("MuJoCo Joint Position vs Real Joint Positions")

total_timesteps = 100
freq = 2
timestep = np.arange(total_timesteps)
desired_joint_trag = np.sin(2*np.pi*freq*(timestep/total_timesteps))
ax[0,0].set_title('Joint_1')
#ax[0,0].plot(timestep, desired_joint_trag, 'b')
ax[0,0].plot(timestep, mujoco_joint_1, 'r')
#ax[0,0].plot(timestep, gazebo_joint_1, 'g')
ax[0,0].plot(timestep, real_joint_1, 'c')
ax[0,0].set_ylabel('Joint Angles (radian)')
ax[0,0].set_xlabel('Timesteps')
#ax[0,0].legend(['Desired', 'Mujoco', 'Gazebo', 'Real'])
ax[0,0].legend(['MuJoCo', 'Real'])

ax[0,1].set_title('Joint_2')
#ax[0,1].plot(timestep, desired_joint_trag*0.7, 'b')
ax[0,1].plot(timestep, mujoco_joint_2, 'r')
#ax[0,1].plot(timestep, gazebo_joint_2, 'g')
ax[0,1].plot(timestep, real_joint_2, 'c')
ax[0,1].set_ylabel('Joint Angles (radian)')
ax[0,1].set_xlabel('Timesteps')
#ax[0,1].legend(['Desired', 'Mujoco', 'Gazebo', 'Real'])
ax[0,1].legend(['MuJoCo', 'Real'])

ax[1,0].set_title('Joint_3')
#ax[1,0].plot(timestep, desired_joint_trag, 'b')
ax[1,0].plot(timestep, mujoco_joint_3, 'r')
#ax[1,0].plot(timestep, gazebo_joint_3, 'g')
ax[1,0].plot(timestep, real_joint_3, 'c')
ax[1,0].set_ylabel('Joint Angles (radian)')
ax[1,0].set_xlabel('Timesteps')
#ax[1,0].legend(['Desired', 'Mujoco', 'Gazebo', 'Real'])
ax[1,0].legend(['MuJoCo', 'Real'])

ax[1,1].set_title('Joint_4')
#ax[1,1].plot(timestep, desired_joint_trag, 'b')
ax[1,1].plot(timestep, mujoco_joint_4, 'r')
#ax[1,1].plot(timestep, gazebo_joint_4, 'g')
ax[1,1].plot(timestep, real_joint_4, 'c')
ax[1,1].set_ylabel('Joint Angles (radian)')
ax[1,1].set_xlabel('Timesteps')
#ax[1,1].legend(['Desired', 'Mujoco', 'Gazebo', 'Real'])
ax[1,1].legend(['MuJoCo', 'Real'])

plt.subplots_adjust(left=0.125,
                    bottom=0.1,
                    right=0.9,
                    top=0.9,
                    wspace=0.2,
                    hspace=0.35)

plt.show()
